### ISSUE TITLE
"substatitive" suppose to be "substantive"

### ISSUE THREAD

**Issue by AndyHubert** [translationCoreApps/word-aligner#14]
`substatitive_adj` appears in both src/js/utils/morphCodeLocalizationMap.js and __tests__/fixtures/morphs/all-titus-morphs.json, and seems to be a misspelling of `substantive_adj`.

**Comment by PhotoNomad0** [comment]
@AndyHubert - It looks like this was already fixed in latest master and develop branch (see https://github.com/translationCoreApps/word-aligner/blob/develop/src/js/utils/morphCodeLocalizationMap.js#L10).  Where are you seeing the problem?

**Comment by AndyHubert** [comment]
In a link sent to me by Jesse. It must have been a pull request comparison
or the like. Sorry I didn't check the latest master first.

**Comment by PhotoNomad0** [comment]
No problem, we appreciate the help in checking for mistakes.  FYI - we are beginning to standardize on the develop branch having the latest code on all our node modules and tools.  We will only merge to master when we make a release.
